# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MplMainWindow(object):
    def setupUi(self, MplMainWindow):
        MplMainWindow.setObjectName("MplMainWindow")
        MplMainWindow.resize(1006, 707)
        self.mplcentralwidget = QtWidgets.QWidget(MplMainWindow)
        self.mplcentralwidget.setObjectName("mplcentralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.mplcentralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1021, 701))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 10, 1001, 661))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_34 = QtWidgets.QLabel(self.tab_4)
        self.label_34.setGeometry(QtCore.QRect(1, 18, 991, 371))
        self.label_34.setObjectName("label_34")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_8.setGeometry(QtCore.QRect(400, 380, 201, 81))
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget_3.addTab(self.tab_4, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.textEdit = QtWidgets.QTextEdit(self.tab_9)
        self.textEdit.setGeometry(QtCore.QRect(580, 50, 371, 331))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.tab_9)
        self.label.setGeometry(QtCore.QRect(30, 50, 511, 71))
        self.label.setStyleSheet("font-size:18px;")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.tab_9)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 491, 261))
        self.label_3.setStyleSheet("font-size:18px;")
        self.label_3.setObjectName("label_3")
        self.label_task_res_1 = QtWidgets.QLabel(self.tab_9)
        self.label_task_res_1.setGeometry(QtCore.QRect(580, 420, 371, 51))
        self.label_task_res_1.setStyleSheet("font-size:20px;")
        self.label_task_res_1.setText("")
        self.label_task_res_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task_res_1.setObjectName("label_task_res_1")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_4 = QtWidgets.QLabel(self.tab_10)
        self.label_4.setGeometry(QtCore.QRect(30, 50, 551, 71))
        self.label_4.setStyleSheet("font-size:18px;")
        self.label_4.setObjectName("label_4")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_10)
        self.textEdit_2.setGeometry(QtCore.QRect(580, 50, 371, 331))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_5 = QtWidgets.QLabel(self.tab_10)
        self.label_5.setGeometry(QtCore.QRect(30, 70, 541, 261))
        self.label_5.setStyleSheet("font-size:18px;")
        self.label_5.setObjectName("label_5")
        self.label_task_res_2 = QtWidgets.QLabel(self.tab_10)
        self.label_task_res_2.setGeometry(QtCore.QRect(580, 420, 371, 51))
        self.label_task_res_2.setStyleSheet("font-size:20px;")
        self.label_task_res_2.setText("")
        self.label_task_res_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task_res_2.setObjectName("label_task_res_2")
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.label_16 = QtWidgets.QLabel(self.tab_11)
        self.label_16.setGeometry(QtCore.QRect(30, 50, 551, 71))
        self.label_16.setStyleSheet("font-size:18px;")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_11)
        self.label_17.setGeometry(QtCore.QRect(30, 70, 541, 261))
        self.label_17.setStyleSheet("font-size:18px;")
        self.label_17.setObjectName("label_17")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab_11)
        self.textEdit_7.setGeometry(QtCore.QRect(580, 50, 371, 331))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_task_res_3 = QtWidgets.QLabel(self.tab_11)
        self.label_task_res_3.setGeometry(QtCore.QRect(580, 420, 371, 51))
        self.label_task_res_3.setStyleSheet("font-size:20px;")
        self.label_task_res_3.setText("")
        self.label_task_res_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task_res_3.setObjectName("label_task_res_3")
        self.tabWidget_3.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.textEdit_8 = QtWidgets.QTextEdit(self.tab_12)
        self.textEdit_8.setGeometry(QtCore.QRect(580, 50, 371, 331))
        self.textEdit_8.setObjectName("textEdit_8")
        self.label_18 = QtWidgets.QLabel(self.tab_12)
        self.label_18.setGeometry(QtCore.QRect(30, 50, 551, 71))
        self.label_18.setStyleSheet("font-size:18px;")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_12)
        self.label_19.setGeometry(QtCore.QRect(30, 70, 541, 261))
        self.label_19.setStyleSheet("font-size:18px;")
        self.label_19.setObjectName("label_19")
        self.label_task_res_4 = QtWidgets.QLabel(self.tab_12)
        self.label_task_res_4.setGeometry(QtCore.QRect(580, 420, 371, 51))
        self.label_task_res_4.setStyleSheet("font-size:20px;")
        self.label_task_res_4.setText("")
        self.label_task_res_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task_res_4.setObjectName("label_task_res_4")
        self.tabWidget_3.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.label_20 = QtWidgets.QLabel(self.tab_13)
        self.label_20.setGeometry(QtCore.QRect(30, 50, 551, 71))
        self.label_20.setStyleSheet("font-size:18px;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_13)
        self.label_21.setGeometry(QtCore.QRect(30, 70, 541, 261))
        self.label_21.setStyleSheet("font-size:18px;")
        self.label_21.setObjectName("label_21")
        self.textEdit_9 = QtWidgets.QTextEdit(self.tab_13)
        self.textEdit_9.setGeometry(QtCore.QRect(580, 50, 371, 331))
        self.textEdit_9.setObjectName("textEdit_9")
        self.label_task_res_5 = QtWidgets.QLabel(self.tab_13)
        self.label_task_res_5.setGeometry(QtCore.QRect(580, 420, 371, 51))
        self.label_task_res_5.setStyleSheet("font-size:20px;")
        self.label_task_res_5.setText("")
        self.label_task_res_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task_res_5.setObjectName("label_task_res_5")
        self.tabWidget_3.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.pushButton = QtWidgets.QPushButton(self.tab_14)
        self.pushButton.setGeometry(QtCore.QRect(60, 50, 471, 131))
        self.pushButton.setStyleSheet("font-size:25px;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.tab_14)
        self.label_2.setGeometry(QtCore.QRect(260, 400, 241, 101))
        self.label_2.setObjectName("label_2")
        self.label_res_1 = QtWidgets.QLabel(self.tab_14)
        self.label_res_1.setGeometry(QtCore.QRect(470, 400, 251, 101))
        self.label_res_1.setStyleSheet("font-size:30px;")
        self.label_res_1.setText("")
        self.label_res_1.setObjectName("label_res_1")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_6.setGeometry(QtCore.QRect(630, 50, 241, 131))
        self.pushButton_6.setStyleSheet("font-size:25px;\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget_3.addTab(self.tab_14, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 10, 1001, 661))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_33 = QtWidgets.QLabel(self.tab_3)
        self.label_33.setGeometry(QtCore.QRect(0, 80, 991, 371))
        self.label_33.setObjectName("label_33")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(399, 442, 201, 81))
        self.pushButton_7.setObjectName("pushButton_7")
        self.tabWidget_4.addTab(self.tab_3, "")
        self.tab_27 = QtWidgets.QWidget()
        self.tab_27.setObjectName("tab_27")
        self.textEdit_10 = QtWidgets.QTextEdit(self.tab_27)
        self.textEdit_10.setGeometry(QtCore.QRect(580, 50, 371, 331))
        self.textEdit_10.setObjectName("textEdit_10")
        self.label_22 = QtWidgets.QLabel(self.tab_27)
        self.label_22.setGeometry(QtCore.QRect(30, 50, 511, 71))
        self.label_22.setStyleSheet("font-size:18px;")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_27)
        self.label_23.setGeometry(QtCore.QRect(30, 70, 491, 261))
        self.label_23.setStyleSheet("font-size:18px;")
        self.label_23.setObjectName("label_23")
        self.label_task_res_6 = QtWidgets.QLabel(self.tab_27)
        self.label_task_res_6.setGeometry(QtCore.QRect(580, 420, 371, 51))
        self.label_task_res_6.setStyleSheet("font-size:20px;")
        self.label_task_res_6.setText("")
        self.label_task_res_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task_res_6.setObjectName("label_task_res_6")
        self.tabWidget_4.addTab(self.tab_27, "")
        self.tab_28 = QtWidgets.QWidget()
        self.tab_28.setObjectName("tab_28")
        self.label_24 = QtWidgets.QLabel(self.tab_28)
        self.label_24.setGeometry(QtCore.QRect(30, 50, 551, 71))
        self.label_24.setStyleSheet("font-size:18px;")
        self.label_24.setObjectName("label_24")
        self.textEdit_11 = QtWidgets.QTextEdit(self.tab_28)
        self.textEdit_11.setGeometry(QtCore.QRect(580, 50, 371, 331))
        self.textEdit_11.setObjectName("textEdit_11")
        self.label_25 = QtWidgets.QLabel(self.tab_28)
        self.label_25.setGeometry(QtCore.QRect(30, 70, 541, 261))
        self.label_25.setStyleSheet("font-size:18px;")
        self.label_25.setObjectName("label_25")
        self.label_task_res_7 = QtWidgets.QLabel(self.tab_28)
        self.label_task_res_7.setGeometry(QtCore.QRect(580, 420, 371, 51))
        self.label_task_res_7.setStyleSheet("font-size:20px;")
        self.label_task_res_7.setText("")
        self.label_task_res_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task_res_7.setObjectName("label_task_res_7")
        self.tabWidget_4.addTab(self.tab_28, "")
        self.tab_29 = QtWidgets.QWidget()
        self.tab_29.setObjectName("tab_29")
        self.label_26 = QtWidgets.QLabel(self.tab_29)
        self.label_26.setGeometry(QtCore.QRect(30, 50, 551, 71))
        self.label_26.setStyleSheet("font-size:18px;")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_29)
        self.label_27.setGeometry(QtCore.QRect(30, 70, 541, 261))
        self.label_27.setStyleSheet("font-size:18px;")
        self.label_27.setObjectName("label_27")
        self.textEdit_12 = QtWidgets.QTextEdit(self.tab_29)
        self.textEdit_12.setGeometry(QtCore.QRect(580, 50, 371, 331))
        self.textEdit_12.setObjectName("textEdit_12")
        self.label_task_res_8 = QtWidgets.QLabel(self.tab_29)
        self.label_task_res_8.setGeometry(QtCore.QRect(580, 420, 371, 51))
        self.label_task_res_8.setStyleSheet("font-size:20px;")
        self.label_task_res_8.setText("")
        self.label_task_res_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task_res_8.setObjectName("label_task_res_8")
        self.tabWidget_4.addTab(self.tab_29, "")
        self.tab_30 = QtWidgets.QWidget()
        self.tab_30.setObjectName("tab_30")
        self.textEdit_13 = QtWidgets.QTextEdit(self.tab_30)
        self.textEdit_13.setGeometry(QtCore.QRect(580, 50, 371, 331))
        self.textEdit_13.setObjectName("textEdit_13")
        self.label_28 = QtWidgets.QLabel(self.tab_30)
        self.label_28.setGeometry(QtCore.QRect(30, 50, 551, 71))
        self.label_28.setStyleSheet("font-size:18px;")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_30)
        self.label_29.setGeometry(QtCore.QRect(30, 70, 541, 261))
        self.label_29.setStyleSheet("font-size:18px;")
        self.label_29.setObjectName("label_29")
        self.label_task_res_9 = QtWidgets.QLabel(self.tab_30)
        self.label_task_res_9.setGeometry(QtCore.QRect(580, 420, 371, 51))
        self.label_task_res_9.setStyleSheet("font-size:20px;")
        self.label_task_res_9.setText("")
        self.label_task_res_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task_res_9.setObjectName("label_task_res_9")
        self.tabWidget_4.addTab(self.tab_30, "")
        self.tab_31 = QtWidgets.QWidget()
        self.tab_31.setObjectName("tab_31")
        self.label_30 = QtWidgets.QLabel(self.tab_31)
        self.label_30.setGeometry(QtCore.QRect(30, 50, 551, 71))
        self.label_30.setStyleSheet("font-size:18px;")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_31)
        self.label_31.setGeometry(QtCore.QRect(30, 70, 541, 261))
        self.label_31.setStyleSheet("font-size:18px;")
        self.label_31.setObjectName("label_31")
        self.textEdit_14 = QtWidgets.QTextEdit(self.tab_31)
        self.textEdit_14.setGeometry(QtCore.QRect(580, 50, 371, 331))
        self.textEdit_14.setObjectName("textEdit_14")
        self.label_task_res_10 = QtWidgets.QLabel(self.tab_31)
        self.label_task_res_10.setGeometry(QtCore.QRect(580, 420, 371, 51))
        self.label_task_res_10.setStyleSheet("font-size:20px;")
        self.label_task_res_10.setText("")
        self.label_task_res_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task_res_10.setObjectName("label_task_res_10")
        self.tabWidget_4.addTab(self.tab_31, "")
        self.tab_32 = QtWidgets.QWidget()
        self.tab_32.setObjectName("tab_32")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_32)
        self.pushButton_4.setGeometry(QtCore.QRect(70, 50, 471, 131))
        self.pushButton_4.setStyleSheet("font-size:25px;\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_32 = QtWidgets.QLabel(self.tab_32)
        self.label_32.setGeometry(QtCore.QRect(260, 400, 241, 101))
        self.label_32.setObjectName("label_32")
        self.label_res_2 = QtWidgets.QLabel(self.tab_32)
        self.label_res_2.setGeometry(QtCore.QRect(470, 400, 251, 101))
        self.label_res_2.setStyleSheet("font-size:30px;")
        self.label_res_2.setText("")
        self.label_res_2.setObjectName("label_res_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_32)
        self.pushButton_5.setGeometry(QtCore.QRect(630, 52, 241, 131))
        self.pushButton_5.setStyleSheet("font-size:25px;\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget_4.addTab(self.tab_32, "")
        self.tabWidget.addTab(self.tab_2, "")
        MplMainWindow.setCentralWidget(self.mplcentralwidget)
        self.actionOpen = QtWidgets.QAction(MplMainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(MplMainWindow)
        self.actionQuit.setObjectName("actionQuit")

        self.retranslateUi(MplMainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MplMainWindow)

    def retranslateUi(self, MplMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MplMainWindow.setWindowTitle(_translate("MplMainWindow", "Клавиатурный тренажер"))
        self.label_34.setText(_translate("MplMainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Тренажер по истории</span></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:14pt;\">Вам предстоит выполнить 5 простых заданий, используя знания по этой теме</span></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:14pt;\">Желаем удачи</span></p></body></html>"))
        self.pushButton_8.setText(_translate("MplMainWindow", "Перейти к задачам"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), _translate("MplMainWindow", "Старт"))
        self.textEdit.setHtml(_translate("MplMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("MplMainWindow", "1. Перепечатайте текст из «Слово о полку Игореве»:\n"
"\n"
""))
        self.label_3.setText(_translate("MplMainWindow", "Не пора ль нам, братия, начать\n"
"О походе Игоревом слово,\n"
"Чтоб старинной речью рассказать\n"
"Про деянья князя удалого?\n"
"А воспеть нам, братия, его -\n"
"В похвалу трудам его и ранам -\n"
"По былинам времени сего,\n"
"Не гоняясь мыслью за Бояном."))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MplMainWindow", "1"))
        self.label_4.setText(_translate("MplMainWindow", "2. Перепечатайте текст из «Meditations» Markus Aurelius\n"
""))
        self.textEdit_2.setHtml(_translate("MplMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_5.setText(_translate("MplMainWindow", "When you wake up in the morning, tell yourself: The\n"
"people I deal with today will be meddling, ungrateful,\n"
"arrogant, dishonest, jealous, and surly. They are like this\n"
"because they can\'t tell good from evil.\n"
""))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MplMainWindow", "2"))
        self.label_16.setText(_translate("MplMainWindow", "3. Перепечатайте часть статьи из Википедии"))
        self.label_17.setText(_translate("MplMainWindow", "Veni, vidi, vici (\"Пришёл, увидел, победил\") - крылатое \n"
"латинское выражение, слова, которыми, Гай Юлий\n"
"Цезарь в августе 47 года до н. э. уведомил своего\n"
"друга Гая Матия в Риме о победе\n"
""))
        self.textEdit_7.setHtml(_translate("MplMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), _translate("MplMainWindow", "3"))
        self.textEdit_8.setHtml(_translate("MplMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_18.setText(_translate("MplMainWindow", "4. Напишите к какому веку принадлежит год\n"
""))
        self.label_19.setText(_translate("MplMainWindow", "1476 + 324\n"
""))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_12), _translate("MplMainWindow", "4"))
        self.label_20.setText(_translate("MplMainWindow", "5. Напишите текст без ошибок\n"
""))
        self.label_21.setText(_translate("MplMainWindow", "Битва, известная как \"Ледовое побоище\",\n"
"состоялась в 1279 году\n"
""))
        self.textEdit_9.setHtml(_translate("MplMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), _translate("MplMainWindow", "5"))
        self.pushButton.setText(_translate("MplMainWindow", "Узнать результат"))
        self.label_2.setText(_translate("MplMainWindow", "<html><head/><body><p><span style=\" font-size:28pt;\">Оценка: </span></p></body></html>"))
        self.pushButton_6.setText(_translate("MplMainWindow", "Очистить"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_14), _translate("MplMainWindow", "Проверить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MplMainWindow", "История"))
        self.label_33.setText(_translate("MplMainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Тренажер по обществознанию</span></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:14pt;\">Вам предстоит выполнить 5 простых заданий, используя знания по этой теме</span></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:14pt;\">Желаем удачи</span></p></body></html>"))
        self.pushButton_7.setText(_translate("MplMainWindow", "Перейти к задачам"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_3), _translate("MplMainWindow", "Старт"))
        self.textEdit_10.setHtml(_translate("MplMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_22.setText(_translate("MplMainWindow", "1. Перепечатайте текст из Википедии"))
        self.label_23.setText(_translate("MplMainWindow", "Социальная стратификация - одно из ключевых\n"
"понятий социологии, обозначающее систему\n"
"признаков и критериев социального расслоения"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_27), _translate("MplMainWindow", "1"))
        self.label_24.setText(_translate("MplMainWindow", "2. Rewrite text from Wikipedia "))
        self.textEdit_11.setHtml(_translate("MplMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_25.setText(_translate("MplMainWindow", "Sociology is a social science that focuses on society,\n"
"human social behaviour, patterns of social relationships"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_28), _translate("MplMainWindow", "2"))
        self.label_26.setText(_translate("MplMainWindow", "3. Перепечатайте часть статьи из Википедии"))
        self.label_27.setText(_translate("MplMainWindow", "Freetrading - направление в экономической теории,\n"
"провозглашающее свободу торговли"))
        self.textEdit_12.setHtml(_translate("MplMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_29), _translate("MplMainWindow", "3"))
        self.textEdit_13.setHtml(_translate("MplMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_28.setText(_translate("MplMainWindow", "4. Решите экономическую задачу"))
        self.label_29.setText(_translate("MplMainWindow", "Cколько тыс рублей останется у Ивана после вычета\n"
"НДФЛ, если он выиграл в лотерею 1 млн рублей \n"
""))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_30), _translate("MplMainWindow", "4"))
        self.label_30.setText(_translate("MplMainWindow", "5. Напишите текст без ошибок\n"
""))
        self.label_31.setText(_translate("MplMainWindow", "Консерватизм - философское и общественно-\n"
"политическое течение, провозглашающее\n"
"непоколебимость прав и личных свобод человека\n"
""))
        self.textEdit_14.setHtml(_translate("MplMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_31), _translate("MplMainWindow", "5"))
        self.pushButton_4.setText(_translate("MplMainWindow", "Узнать результат"))
        self.label_32.setText(_translate("MplMainWindow", "<html><head/><body><p><span style=\" font-size:28pt;\">Оценка: </span></p></body></html>"))
        self.pushButton_5.setText(_translate("MplMainWindow", "Очистить"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_32), _translate("MplMainWindow", "Проверить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MplMainWindow", "Обществознание"))
        self.actionOpen.setText(_translate("MplMainWindow", "Open"))
        self.actionQuit.setText(_translate("MplMainWindow", "Quit"))
